name: 'CSG Action'
description: 'Check if ManualSteps or Pre/Post Deployment files are present'
author: 'CSG'
inputs:
  repo:
    description: 'The target `owner/repo` to manage the check run on (defaults to the current repository'
    required: false
  sha:
    description: 'The target commits SHA (defaults to the current commit)'
    required: false
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  name:
    description: 'The name of the check to create (incompatible with `check_id`)'
    required: false
  conclusion:
    description: 'The conclusion of your check'
    required: false
  status:
    description: 'The status of your check'
    required: false
    default: completed
  output_title:
    description: 'The output title of your check'
    required: false
  output_summary:
    description: 'The output summary of your check'
    required: false
  pull_request:
    description: 'The number of the pull request'
    required: false
  file_name:
    description: 'The name of the branch of the current pull request'
    required: true
    default: 
outputs:
  file_path:
    description: 'The fully-formed name of the branch'
  
runs:
  using: 'node16'
  main: 'dist/index.js'